parameters:
    vs_websocket.document_root: "%kernel.project_dir%/public"
    vs_websocket.exeption_trace: "%env(bool:WEBSOCKET_EXCEPTION_TRACE)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    vs_websocket_server_command:
        class: Vankosoft\WebsocketBundle\Command\WebsocketServerCommand
        arguments:
            - '@service_container'
            - '@vs_websocket_logger'
            - "%vs_websocket.document_root%"
        tags:
            - 'console.command'
    
    vs_websocket_server_handler:
        class: Vankosoft\WebsocketBundle\Websocket\Server\ServerHandler
        arguments:
            - '@vs_websocket_logger'
            - '@serializer'
            - "%vs_websocket.exeption_trace%"
